// Outils — débloquent la récolte manuelle d'une ressource pour tous les joueurs
// + charrette pour le transport
export const upgradesTools = {
  hache: {
    name: '🪓 Hache',
    desc: 'Permet à tout le monde de couper du bois',
    baseCost: {},
    growth: 1,
    repeatable: false,
    max: 1,
  },
  pioche: {
    name: '⛏️ Pioche',
    desc: 'Permet à tout le monde de miner la pierre',
    baseCost: { wood: 20 },
    growth: 1,
    repeatable: false,
    max: 1,
  },
  pioche_stellaire: {
    name: '⛏️ Pioche stellaire',
    desc: 'Améliore la pioche — débloque la construction du puits',
    costs: [{ stone: 40, meteorite: 8 }],
    repeatable: false,
    max: 1,
  },
  fishing_rod: {
    name: '🎣 Canne à pêche',
    desc: 'Permet à tout le monde de pêcher',
    baseCost: { wood: 15, stone: 10 },
    growth: 1,
    repeatable: false,
    max: 1,
  },
  faucille: {
    name: '🌾 Faucille',
    desc: 'Permet à tout le monde de cueillir des baies',
    baseCost: { wood: 15, stone: 10 },
    growth: 1,
    repeatable: false,
    max: 1,
  },
  charrette: {
    name: '🛒 Charrette',
    desc: "Transporter les ressources jusqu'au village",
    baseCost: { wood: 18 },
    growth: 2,
    repeatable: true,
    max: 4,
  },
  bag_size: {
    name: '🎒 Grand sac',
    desc: 'Agrandit le sac à dos de tous les joueurs (+3 emplacements)',
    costs: [{ wood: 15 }, { wood: 25, stone: 10 }, { wood: 40, stone: 20 }],
    repeatable: true,
    max: 3,
  },
  cart_size: {
    name: '🛒 Grande charrette',
    desc: 'Augmente la capacité de stockage de la charrette (+9 emplacements)',
    costs: [{ wood: 20, stone: 8 }, { wood: 35, stone: 18 }, { wood: 60, stone: 30 }],
    repeatable: true,
    max: 3,
  },
}
