import { C } from '../palette.js'

export const buildingDefs = {
  house: {
    rows: [
      '........RR........',
      '.......RRRR.......',
      '......RRRRRR......',
      '.....RRRRRRRR.....',
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '..WWWWWWWWWWWWWW..',
      '..WWWWWWWWWWWWWW..',
      '..WGgWWWWWWWWGgW..',
      '..WGgWWWWWWWWGgW..',
      '..WWWWWWWWWWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..wwwwwwwwwwwwww..',
    ],
    pal: { R: C.roof, r: C.roof_d, W: C.wall, w: C.wall_d, G: C.wall_d, g: C.glass, D: C.door },
  },
  cabin: {
    rows: [
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.WWGgWWWWWWWWWWWW.',
      '.WWGgWWWWWDDDWWWW.',
      '.wwwwwwwwwDDDwwww.',
      '.WWWWWWWWWDDDWWWW.',
      '.WWWWWWWWWDDDWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.LLLL.WWWWWWWWWWW.',
      '.LLLL.wwwwwwwwwww.',
    ],
    pal: { R: C.roofbrown, r: C.roofbrown_d, W: C.wood, w: C.wood_d, G: C.wood_d, g: C.glass, D: C.door, L: C.wood_l },
  },
  hut: {
    rows: [
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.WWGgWWWWDDDWWWWW.',
      '.WWGgWWWWDDDWWWWW.',
      '.wwwwwwwwDDDwwwww.',
      '.WWWWWWWWDDDWWWWW.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '..pp..pp..pp..pp.',
      '..pp..pp..pp..pp.',
    ],
    pal: { R: C.roofb, r: C.roofb_d, W: C.wood, w: C.wood_d, G: C.wood_d, g: C.glass, D: C.door, p: C.wood_d },
  },
  chalet: {
    rows: [
      '..........cc..........',
      '.........cRRc.........',
      '.......RRRRRRRRRr.....',
      '......RRRRRRRRRRRr....',
      '.....RRRRRRRRRRRRRr...',
      '....rRRRRRRRRRRRRRRr..',
      '...rRRRRRRRRRRRRRRRrr.',
      '..rrrrrrrrrrrrrrrrrrr.',
      '..WWWWWWWWWWWWWWWWWWW.',
      '..WwWWWWWWWWWWWWWwWWW.',
      '..WGgWWWFFWWFFWWWGgWW.',
      '..WGgWWWffWWffWWWGgWW.',
      '..WwWWWWWDDWWWWWwWWW..',
      '..SSSSSSSSSSSSSSSSss..',
      '..sSSSSSSSSSSSSSSSss..',
      '..ssssssssssssssssss..',
    ],
    pal: {
      R: '#8a4e22', r: '#5c3010',
      W: '#cb8a42', w: '#9a6228',
      S: '#a0a2aa', s: '#707280',
      D: '#3a2818',
      G: '#4090b2', g: '#c0e6f8',
      c: '#70737e',
      F: '#e88ab2', f: '#3a8028',
    },
  },
  quarry: {
    rows: [
      '..............TT..',
      '..TttttttttttTTT.',
      '...r...........T.',
      '...r...........T.',
      '...SSSS........T.',
      '...SSdd........T.',
      '...dddd........T.',
      '..TTTTTTTTTTTTT..',
      '.WWWWWWWWWWWWWWWW',
      '.WwwwwwwwwwwwwwwW',
      '.SSSSSSSSSSSSSSSS',
      '..ssssssssssssss.',
    ],
    pal: {
      T: '#8a5c34', t: '#5a3a20',
      W: '#cb8a42', w: '#9a6228',
      S: C.rock_l, d: C.rock_d,
      r: '#2c1c0c',
    },
  },
  garden: {
    rows: [
      '.bb.bb.bb.bb.',
      'bBBbBBbBBbBBb',
      'bBrBBrBBrBBrB',
      'bBBBBBBBBBBBb',
      'bBrBBrBBrBBrB',
      'bBBbBBbBBbBBb',
      '.bb.bb.bb.bb.',
      '..............',
      '..pppppppppp..',
      '...eeeeeeee...',
    ],
    pal: {
      b: '#4a7838', B: '#5e9a48', r: '#cc3030',
      p: '#8a5c34', e: '#7a5030',
    },
  },
  astronomy: {
    rows: [
      '..........ff..........',
      '.......hDDDDDDh.......',
      '......hDDDDDDDDDh.....',
      '.....DDDdDDDDDdDDD....',
      '.....dDDDDDDDDDdd.....',
      '......dDDDDDDDdd......',
      '....rrrrrrrrrrrrrr....',
      '....SSSSSSSSSSSSSS....',
      '....SoSSSSSSSSSSoS....',
      '....SoSSSSSSSSSSoS....',
      '....SSSSSSSSSSSSSS....',
      '....SsSSSSSSSSSSsS....',
      '....SSSSSSSSSSSSSS....',
      '....SoSSSSSSSSSSoS....',
      '....SoSSSSSSSSSSoS....',
      '....SSSSSSSSSSSSSS....',
      '...SSSSSSSSSSSSSSSS...',
      '...SsSSSSSSSSSSSSsS...',
      '...SSSSSSSSSSSSSSSS...',
      '...SoSSSSSSSSSSSSoS...',
      '...SoSSSSSSSSSSSSoS...',
      '...SSSSSSSSSSSSSSSS...',
      '..SSSSSSSSSSSSSSSSSS..',
      '..ssssssssssssssssss..',
      '..ssssssssssssssssss..',
      '...ssssssssssssssss...',
    ],
    pal: {
      f: '#f0eaff',
      h: '#c8bcff',
      D: '#9080e0',
      d: '#5848a8',
      r: '#2e2640',
      S: '#b4b6c2',
      s: '#888a98',
      o: '#1a1828',
    },
  },
  workshop: {
    rows: [
      '....rRRRRRRRRr........',
      '..rRRRRRRRRRRRrr......',
      '.rrrrrrrrrrrrrrr.lLLLl',
      '..WWWWWWWWWWWWW..LLLLL',
      '..WwWWWWWWWWWWW..lLLLl',
      '..WGgWWWWWWWGgW..LLLLL',
      '..WGgWWWWWWWGgW..lLLLl',
      '..WwWWWWWWWWWWW..LLLLL',
      '..WWWWdDDDDwWWW..lLLLl',
      '..WWWWDbbbbDWWW..LLLLL',
      '..WWWWDbbEbDWWW..lLLLl',
      '..WWWWDbbbbDWWW..LLLLL',
      '..WWWWwDDDDwWWW..lLLLl',
      '..wwwwwwwwwwwww..LLLLL',
      '..wwwwwwwwwwwww..lLLLl',
    ],
    pal: {
      R: C.roofbrown,
      r: C.roofbrown_d,
      W: C.wood_l,
      w: C.wood_d,
      G: C.wood_d,
      g: C.glass,
      D: C.door,
      b: '#201408',
      E: '#9a7050',
      L: '#d4b880',
      l: '#7a5030',
    },
  },
  telescope: {
    rows: [
      '......TT',
      '.....TTT',
      '....TTTT',
      '...ttttt',
      '....t...',
      '...ttt..',
      '..t.t...',
    ],
    pal: { T: '#d0d0e0', t: '#606078' },
  },
}
