import { C } from '../palette.js'

export const buildingDefs = {
  house: {
    rows: [
      '........RR........',
      '.......RRRR.......',
      '......RRRRRR......',
      '.....RRRRRRRR.....',
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '..WWWWWWWWWWWWWW..',
      '..WWWWWWWWWWWWWW..',
      '..WGgWWWWWWWWGgW..',
      '..WGgWWWWWWWWGgW..',
      '..WWWWWWWWWWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..wwwwwwwwwwwwww..',
    ],
    pal: { R: C.roof, r: C.roof_d, W: C.wall, w: C.wall_d, G: C.wall_d, g: C.glass, D: C.door },
  },
  cabin: {
    rows: [
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.WWGgWWWWWWWWWWWW.',
      '.WWGgWWWWWDDDWWWW.',
      '.wwwwwwwwwDDDwwww.',
      '.WWWWWWWWWDDDWWWW.',
      '.WWWWWWWWWDDDWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.LLLL.WWWWWWWWWWW.',
      '.LLLL.wwwwwwwwwww.',
    ],
    pal: { R: C.roofbrown, r: C.roofbrown_d, W: C.wood, w: C.wood_d, G: C.wood_d, g: C.glass, D: C.door, L: C.wood_l },
  },
  hut: {
    rows: [
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.WWGgWWWWDDDWWWWW.',
      '.WWGgWWWWDDDWWWWW.',
      '.wwwwwwwwDDDwwwww.',
      '.WWWWWWWWDDDWWWWW.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '..pp..pp..pp..pp.',
      '..pp..pp..pp..pp.',
    ],
    pal: { R: C.roofb, r: C.roofb_d, W: C.wood, w: C.wood_d, G: C.wood_d, g: C.glass, D: C.door, p: C.wood_d },
  },
  chalet: {
    rows: [
      '..........cc..........',
      '.........cRRc.........',
      '.......RRRRRRRRRr.....',
      '......RRRRRRRRRRRr....',
      '.....RRRRRRRRRRRRRr...',
      '....rRRRRRRRRRRRRRRr..',
      '...rRRRRRRRRRRRRRRRrr.',
      '..rrrrrrrrrrrrrrrrrrr.',
      '..WWWWWWWWWWWWWWWWWWW.',
      '..WwWWWWWWWWWWWWWwWWW.',
      '..WGgWWWFFWWFFWWWGgWW.',
      '..WGgWWWffWWffWWWGgWW.',
      '..WwWWWWWDDWWWWWwWWW..',
      '..SSSSSSSSSSSSSSSSss..',
      '..sSSSSSSSSSSSSSSSss..',
      '..ssssssssssssssssss..',
    ],
    pal: {
      R: '#8a4e22', r: '#5c3010',
      W: '#cb8a42', w: '#9a6228',
      S: '#a0a2aa', s: '#707280',
      D: '#3a2818',
      G: '#4090b2', g: '#c0e6f8',
      c: '#70737e',
      F: '#e88ab2', f: '#3a8028',
    },
  },
  quarry: {
    rows: [
      '..............TT..',
      '..TttttttttttTTT.',
      '...r...........T.',
      '...r...........T.',
      '...SSSS........T.',
      '...SSdd........T.',
      '...dddd........T.',
      '..TTTTTTTTTTTTT..',
      '.WWWWWWWWWWWWWWWW',
      '.WwwwwwwwwwwwwwwW',
      '.SSSSSSSSSSSSSSSS',
      '..ssssssssssssss.',
    ],
    pal: {
      T: '#8a5c34', t: '#5a3a20',
      W: '#cb8a42', w: '#9a6228',
      S: C.rock_l, d: C.rock_d,
      r: '#2c1c0c',
    },
  },
  garden: {
    rows: [
      '.bb.bb.bb.bb.',
      'bBBbBBbBBbBBb',
      'bBrBBrBBrBBrB',
      'bBBBBBBBBBBBb',
      'bBrBBrBBrBBrB',
      'bBBbBBbBBbBBb',
      '.bb.bb.bb.bb.',
      '..............',
      '..pppppppppp..',
      '...eeeeeeee...',
    ],
    pal: {
      b: '#4a7838', B: '#5e9a48', r: '#cc3030',
      p: '#8a5c34', e: '#7a5030',
    },
  },
  astronomy: {
    rows: [
      '....DDDDDD....',
      '...DDDDDDDD...',
      '..DDDDDDDDDD..',
      '..ddddddddddd.',
      '..AAAAAAAAAA..',
      '..AaAAAAAAAAA.',
      '..AAAAAAAAAA..',
      '..AaAAAAAAAAA.',
      '..AAAAAAAAAA..',
      '..ssssssssss..',
      '...ssssssss...',
    ],
    pal: { D: '#a090e8', d: '#6858b0', A: '#7868c0', a: '#c0b0f0', s: '#38304a' },
  },
  telescope: {
    rows: [
      '......TT',
      '.....TTT',
      '....TTTT',
      '...ttttt',
      '....t...',
      '...ttt..',
      '..t.t...',
    ],
    pal: { T: '#d0d0e0', t: '#606078' },
  },
}
