import { C } from '../palette.js'

export const buildingDefs = {
  house: {
    rows: [
      '........RR........',
      '.......RRRR.......',
      '......RRRRRR......',
      '.....RRRRRRRR.....',
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '..WWWWWWWWWWWWWW..',
      '..WWWWWWWWWWWWWW..',
      '..WGgWWWWWWWWGgW..',
      '..WGgWWWWWWWWGgW..',
      '..WWWWWWWWWWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..WWWWWDDDDWWWWW..',
      '..wwwwwwwwwwwwww..',
    ],
    pal: { R: C.roof, r: C.roof_d, W: C.wall, w: C.wall_d, G: C.wall_d, g: C.glass, D: C.door },
  },
  cabin: {
    rows: [
      '....RRRRRRRRRR....',
      '...RRRRRRRRRRRR...',
      '..RRRRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrrrr.',
      '.WWWWWWWWWWWWWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.WWGgWWWWWWWWWWWW.',
      '.WWGgWWWWWDDDWWWW.',
      '.wwwwwwwwwDDDwwww.',
      '.WWWWWWWWWDDDWWWW.',
      '.WWWWWWWWWDDDWWWW.',
      '.wwwwwwwwwwwwwwww.',
      '.LLLL.WWWWWWWWWWW.',
      '.LLLL.wwwwwwwwwww.',
    ],
    pal: { R: C.roofbrown, r: C.roofbrown_d, W: C.wood, w: C.wood_d, G: C.wood_d, g: C.glass, D: C.door, L: C.wood_l },
  },
  hut: {
    rows: [
      '.....rRRRRRRRrr.....',
      '...rRRRRRRRRRRRrr...',
      '..rrrrrrrrrrrrrrrr..',
      '..WWWWWWWWWWWWWWWW..',
      '..WwWWWWWWWWWWWWwW..',
      '..WNnNnNnNnNnNnNnW..',
      '..WGgWWWWWWWWWGgW...',
      '..WGgWWWWWWWWWGgW...',
      '..WwWWWWWWWWWWWWwW..',
      '..WWWWWDDDDDWWWWWW..',
      '..WWWWWdddddWWWWWW..',
      '..WWWWWdddddWWWWWW..',
      '..wwwwwwwwwwwwwwww..',
      '..PPPPPPPPPPPPPPPP..',
      '...p...p...p...p....',
    ],
    pal: {
      R: C.roofb,
      r: C.roofb_d,
      W: C.wood,
      w: C.wood_d,
      G: C.wood_d,
      g: C.glass,
      D: C.door,
      d: '#201408',
      N: '#5a8898',
      n: '#3a5868',
      P: '#9a7040',
      p: '#6a4828',
    },
  },
  chalet: {
    rows: [
      '..........cc..........',
      '.........cRRc.........',
      '.......RRRRRRRRRr.....',
      '......RRRRRRRRRRRr....',
      '.....RRRRRRRRRRRRRr...',
      '....rRRRRRRRRRRRRRRr..',
      '...rRRRRRRRRRRRRRRRrr.',
      '..rrrrrrrrrrrrrrrrrrr.',
      '..WWWWWWWWWWWWWWWWWWW.',
      '..WwWWWWWWWWWWWWWwWWW.',
      '..WGgWWWFFWWFFWWWGgWW.',
      '..WGgWWWffWWffWWWGgWW.',
      '..WwWWWWWDDWWWWWwWWW..',
      '..SSSSSSSSSSSSSSSSss..',
      '..sSSSSSSSSSSSSSSSss..',
      '..ssssssssssssssssss..',
    ],
    pal: {
      R: '#8a4e22', r: '#5c3010',
      W: '#cb8a42', w: '#9a6228',
      S: '#a0a2aa', s: '#707280',
      D: '#3a2818',
      G: '#4090b2', g: '#c0e6f8',
      c: '#70737e',
      F: '#e88ab2', f: '#3a8028',
    },
  },
  quarry: {
    rows: [
      '....TTTTTTTTTTTTTT....',
      '....T..............T..',
      '....T.SSSSSSSSSSSS.T..',
      '....T.SoSSSSSSSSoS.T..',
      '....T.SSSoSSSSoSSS.T..',
      '....T.SSSSSSSSSSSS.T..',
      '....T.sSSSSSSSSSSs.T..',
      '....T.ssssssssssss.T..',
      '....TTTTTTTTTTTTTT....',
      '....WWWWWWWWWWWWWWWW..',
      '....WwWWWWDDDDWwWWWW..',
      '....SSSS.SSSSSS.SSSS..',
      '....ssss.ssssss.ssss..',
      '....SSSS.SSSSSS.SSSS..',
    ],
    pal: {
      T: '#7a5028',
      W: C.wood,
      w: C.wood_d,
      D: C.door,
      S: C.rock_l,
      s: C.rock_d,
      o: '#2c1c0c',
    },
  },
  garden: {
    rows: [
      '....FFFFFFFf..........',
      '...FFFFFFFFFf.........',
      '...fffffffffff........',
      '...WWWWWWWWW.bBbBbBbBb',
      '...WGgWWWWWW.bBrBbBrBb',
      '...WGgWWWWWW.bBbBbBbBb',
      '...WWWWDDDWW.bBrBbBrBb',
      '...wwwwwwwww.bBbBbBbBb',
      '...ppppppppppppppppppp',
      '...bBbBbBbBbBbBbBbBbBb',
      '...bBrBbBrBbBrBbBrBbBr',
      '...bBbBbBbBbBbBbBbBbBb',
      '...ppppppppppppppppppp',
      '...bBrBbBrBbBrBbBrBbBr',
    ],
    pal: {
      F: C.roofbrown,
      f: C.roofbrown_d,
      W: C.wood,
      w: C.wood_d,
      G: C.wood_d,
      g: C.glass,
      D: C.door,
      b: '#4a7838',
      B: '#5e9a48',
      r: '#cc3030',
      p: '#8a5c34',
    },
  },
  astronomy: {
    rows: [
      '..........ff..........',
      '.......hDDDDDDh.......',
      '......hDDDDDDDDDh.....',
      '.....DDDdDDDDDdDDD....',
      '.....dDDDDDDDDDdd.....',
      '......dDDDDDDDdd......',
      '....rrrrrrrrrrrrrr....',
      '....SSSSSSSSSSSSSS....',
      '....SoSSSSSSSSSSoS....',
      '....SoSSSSSSSSSSoS....',
      '....SSSSSSSSSSSSSS....',
      '....SsSSSSSSSSSSsS....',
      '....SSSSSSSSSSSSSS....',
      '....SoSSSSSSSSSSoS....',
      '....SoSSSSSSSSSSoS....',
      '....SSSSSSSSSSSSSS....',
      '...SSSSSSSSSSSSSSSS...',
      '...SsSSSSSSSSSSSSsS...',
      '...SSSSSSSSSSSSSSSS...',
      '...SoSSSSSSSSSSSSoS...',
      '...SoSSSSSSSSSSSSoS...',
      '...SSSSSSSSSSSSSSSS...',
      '..SSSSSSSSSSSSSSSSSS..',
      '..ssssssssssssssssss..',
      '..ssssssssssssssssss..',
      '...ssssssssssssssss...',
    ],
    pal: {
      f: '#f0eaff',
      h: '#c8bcff',
      D: '#9080e0',
      d: '#5848a8',
      r: '#2e2640',
      S: '#b4b6c2',
      s: '#888a98',
      o: '#1a1828',
    },
  },
  workshop: {
    rows: [
      '....rRRRRRRRRr........',
      '..rRRRRRRRRRRRrr......',
      '.rrrrrrrrrrrrrrr.lLLLl',
      '..WWWWWWWWWWWWW..LLLLL',
      '..WwWWWWWWWWWWW..lLLLl',
      '..WGgWWWWWWWGgW..LLLLL',
      '..WGgWWWWWWWGgW..lLLLl',
      '..WwWWWWWWWWWWW..LLLLL',
      '..WWWWdDDDDwWWW..lLLLl',
      '..WWWWDbbbbDWWW..LLLLL',
      '..WWWWDbbEbDWWW..lLLLl',
      '..WWWWDbbbbDWWW..LLLLL',
      '..WWWWwDDDDwWWW..lLLLl',
      '..wwwwwwwwwwwww..LLLLL',
      '..wwwwwwwwwwwww..lLLLl',
    ],
    pal: {
      R: C.roofbrown,
      r: C.roofbrown_d,
      W: C.wood_l,
      w: C.wood_d,
      G: C.wood_d,
      g: C.glass,
      D: C.door,
      b: '#201408',
      E: '#9a7050',
      L: '#d4b880',
      l: '#7a5030',
    },
  },
  telescope: {
    rows: [
      '......TT',
      '.....TTT',
      '....TTTT',
      '...ttttt',
      '....t...',
      '...ttt..',
      '..t.t...',
    ],
    pal: { T: '#d0d0e0', t: '#606078' },
  },
}
