import { C } from '../palette.js'

export const villageDefs = {
  castle: {
    rows: [
      'SSS..SSS..SS..SSS..SSS',
      'SSSSSSSSSSSSSSSSSSSSSS',
      'SSSoSSSSSSSSSSSSSSoSSS',
      'SSSSSggSSSSSSSggSSSSSS',
      'SSSSSggSSSSSSSggSSSSSS',
      'SSSSSSSSSSSSSSSSSSSSSS',
      'SSSoSSSSSSSSSSSSSSoSSS',
      'SSSSSSSSSSSSSSSSSSSSSS',
      'SSSSSSSSSdDDdSSSSSSSSS',
      'SSSSSSSSSdDDdSSSSSSSSS',
      'SSSSSSSSSdDDdSSSSSSSSS',
      'SSSSSSSSSdDDdSSSSSSSSS',
      'SSSSSSSSSdDDdSSSSSSSSS',
      'ssssssssssssssssssssss',
      'ssssssssssssssssssssss',
      'ssssssssssssssssssssss',
    ],
    pal: {
      S: '#b0b2be',
      s: '#7e8090',
      o: '#1a1828',
      g: C.glass,
      d: '#3a2840',
      D: '#0e0c18',
    },
  },
  hut_small: {
    rows: [
      '.......RR.......',
      '......RRRR......',
      '.....RRRRRR.....',
      '....RRRRRRRR....',
      '...RRRRRRRRRR...',
      '..RRRRRRRRRRRR..',
      '.rrrrrrrrrrrrrr.',
      '.WWWWWWWWWWWWWW.',
      '.WwWWGgWWDDWWwW.',
      '.WwWWGgWWDDWWwW.',
      '.WwWWWWWWWWWWwW.',
      '.wwwwwwwwwwwwww.',
    ],
    pal: {
      R: C.roofbrown,
      r: C.roofbrown_d,
      W: C.wood,
      w: C.wood_d,
      G: C.wood_d,
      g: C.glass,
      D: C.door,
    },
  },
  campfire: {
    rows: [
      '..........',
      '....yy....',
      '...yoy....',
      '..yooyy...',
      '..yoroy...',
      '..orrroo..',
      '.sSrrrrSs.',
      'sSs.rr.sSs',
      '.ss....ss.',
    ],
    pal: { y: C.fire_y, o: C.fire_o, r: C.fire_r, s: C.rock_d, S: C.rock },
  },
  cart: {
    rows: [
      'h..TTTTTTT.',
      'h..TbbbbBT.',
      'h..TbbbbBT.',
      '...TtTtTtTT',
      '....T....T.',
      '...wWw..wWw',
    ],
    pal: { T: '#cb8a42', t: '#a86a2e', b: '#4a2c10', B: '#3a1e08', h: '#8a5c34', w: '#2c1c0c', W: '#4a3010' },
  },
  cart_2: {
    rows: [
      'h..TTTTTTT.',
      'h..TbPbPbT.',
      'h..TbPbPbT.',
      '...TtTtTtTT',
      '....T....T.',
      '...wWw..wWw',
    ],
    pal: { T: '#d09540', t: '#a87830', b: '#5a3818', P: '#6e4820', h: '#8a5c34', w: '#2c1c0c', W: '#4a3010' },
  },
  cart_3: {
    rows: [
      'h..MMMMMMM.',
      'h..MbbbbMM.',
      'h..MbbbbMM.',
      '...MMMMMMMM',
      '....M....M.',
      '...wWW..wWW',
    ],
    pal: { M: '#8898b0', b: '#3e2c10', h: '#8a5c34', w: '#1e1020', W: '#5878a0' },
  },
}
